services:
  backend:
    build:
      context: go-server
    ports:
      - "8080:8080"

  frontend:
    build:
      context: react-app
      target: development
    volumes:
      - ./react-app:/app
    ports:
      - "5173:5173"

  proxy:
    image: nginx:mainline-alpine3.23-perl
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 127.0.0.1:80:80
    depends_on:
      - backend
      - frontend
